In [3]:
# installation of packages
!pip install --upgrade pip
!pip install pandas
!pip install seaborn

Requirement already satisfied: pip in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (22.0.4)
Requirement already satisfied: pandas in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (1.1.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.15.4 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from pandas) (1.19.1)
Requirement already satisfied: six>=1.5 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.14.0)
Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.8/292.8 KB 5.0 MB/s eta 0:00:0000:01
Requirement already satisfied: matplotlib>=2.2 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from seaborn) (3.3.2)
Requirement already satisfied: scipy>=1.0 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from seaborn) (1.5.0)
Requirement already satisfied: numpy>=1.15 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from seaborn) (1.19.1)
Requirement already satisfied: pandas>=0.23 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from seaborn) (1.1.3)
Requirement already satisfied: certifi>=2020.06.20 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (8.0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: pytz>=2017.2 in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from pandas>=0.23->seaborn) (2020.1)
Requirement already satisfied: six in /Users/zhouchang/miniconda3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.14.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.11.2

In [4]:
# import libraries
import pandas as pd
import numpy as np
import pandas as pd
import sklearn.linear_model as lm
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# load_data
df = pd.read_csv('Data_API.csv')

/Users/zhouchang/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3012: DtypeWarning: Columns (0,1,2,4,6,8,9,10,14,15,20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
# Basic info about the dataframe we loaded from the dataset
display(df.columns)
display(df.shape[0])

Index(['Smart_contract', 'ID_token', 'Transaction_hash', 'Seller_address',
       'Seller_username', 'Buyer_address', 'Buyer_username', 'Image_url_1',
       'Image_url_2', 'Image_url_3', 'Image_url_4', 'Price_Crypto', 'Crypto',
       'Price_USD', 'Name', 'Description', 'Collection', 'Market',
       'Datetime_updated', 'Datetime_updated_seconds', 'Permanent_link',
       'Unique_id_collection', 'Collection_cleaned', 'Category'],
      dtype='object')

6071027

In [26]:
# Group data from the original dataset by category
categories = df["Category"].unique()
for category in categories:
    globals()[category.lower() + "_data"] = df[df["Category"] == category]
display(art_data)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Name,Description,Collection,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category
236210,NaN,19925,0xd907c6bb81c6e1d58edd7484ae0f3a66eb17ae969737...,0x214e0807b739259e432c6d6842fb6c4bc8eae4da,NaN,0x71494a98803ad0bc7b228a14da82f7197665a065,NaN,https://img.cryptokitties.co/0x06012c8cf97bead...,NaN,NaN,...,NaN,NaN,Cryptokitties,Cryptokitties,2017-11-30 00:00:00,2017-11-30 23:59:41,NaN,"('Cryptokitties', '19925')",Cryptokittie,Art
236211,NaN,19737,0x27f16dd55a1aa64248cbd7c48425540bdf7c08afa680...,0x7058cc88746c4d3d3c8df3e364717771ce90ece8,NaN,0x702161763b21e21256c2ec8a79cb581ea39c0af3,NaN,https://img.cryptokitties.co/0x06012c8cf97bead...,NaN,NaN,...,NaN,NaN,Cryptokitties,Cryptokitties,2017-11-30 00:00:00,2017-11-30 23:57:39,NaN,"('Cryptokitties', '19737')",Cryptokittie,Art
236212,NaN,14206,0xc1069a14342ca3c2a940a328e6a90d3e8441c89c7a70...,0x7058cc88746c4d3d3c8df3e364717771ce90ece8,NaN,0xb5cdd02824a1f715cbfb0c26192f811ae3bf4d61,NaN,https://img.cryptokitties.co/0x06012c8cf97bead...,NaN,NaN,...,NaN,NaN,Cryptokitties,Cryptokitties,2017-11-30 00:00:00,2017-11-30 23:57:07,NaN,"('Cryptokitties', '14206')",Cryptokittie,Art
236213,NaN,6948,0x34e41ad7b791143752feb9e42d62ff07cb943a9ff855...,0x79bd592415ff6c91cfe69a7f9cd091354fc65a18,NaN,0xcfb586d08633fc36953be8083b63a7d96d50265b,NaN,https://img.cryptokitties.co/0x06012c8cf97bead...,NaN,NaN,...,NaN,NaN,Cryptokitties,Cryptokitties,2017-11-30 00:00:00,2017-11-30 23:57:01,NaN,"('Cryptokitties', '6948')",Cryptokittie,Art
236214,NaN,19128,0x4f91023b44d99d552bd02b55e16f3eec2d6a4cdfd6f5...,0xf50077dc0a58d5d1cf12c0c900b1365ecaccff24,NaN,0x1625ff3aa126dd7ca468ab9195519e26a9cee53c,NaN,https://img.cryptokitties.co/0x06012c8cf97bead...,NaN,NaN,...,NaN,NaN,Cryptokitties,Cryptokitties,2017-11-30 00:00:00,2017-11-30 23:57:01,NaN,"('Cryptokitties', '19128')",Cryptokittie,Art
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6071012,0xd07dc4262bcdbf85190c01c996b4c06a461d2430,337200,0x004454111cce79f95891140a94a1b8835c0bf79b880f...,0x1070654f48ed83bac77da859556b4f6c27eaec12,EnzoManneli,0x0c544f463600eb7d94b3694f3f3eb171c2f1a93c,riverrunpasteveandadam,https://lh3.googleusercontent.com/oIqHEkBUECLe...,https://ipfs.io/ipfs/QmZdpgxaP2F6yZrjt2wjtgsDR...,https://lh3.googleusercontent.com/oIqHEkBUECLe...,...,Marilyn Selfie Queen 👸,Major Pop Icon Marilyn Monroe...the Selfie Queen.,Rarible,OpenSea,2021-04-01 00:00:00,2021-04-01 00:05:11,https://opensea.io/assets/0xd07dc4262bcdbf8519...,"('Rarible', '337200')",Rari,Art
6071013,0xd07dc4262bcdbf85190c01c996b4c06a461d2430,409157,0xcee218a33a0fc211580389b330c56356d569bea29976...,0x1070654f48ed83bac77da859556b4f6c27eaec12,EnzoManneli,0x0c544f463600eb7d94b3694f3f3eb171c2f1a93c,riverrunpasteveandadam,https://lh3.googleusercontent.com/6MMGbXhASXid...,https://ipfs.io/ipfs/QmNRMq38nHNmk5pPhute6VWeC...,https://lh3.googleusercontent.com/6MMGbXhASXid...,...,Skater Elvis HODLer,Skater Elvis is a HODLer,Rarible,OpenSea,2021-04-01 00:00:00,2021-04-01 00:05:09,https://opensea.io/assets/0xd07dc4262bcdbf8519...,"('Rarible', '409157')",Rari,Art
6071019,0xd07dc4262bcdbf85190c01c996b4c06a461d2430,140105,0xb17d8f87dcd907088cbb8b6762ba34531c2f5abc7458...,0xce1f27b591ca205066ac9257e3cab7b604a457b4,a_guy_from_Melmac,0x99e73a69536f7365fd4f2f2e5391f5daa484b99b,Beldrueger,https://lh3.googleusercontent.com/tq9bi4bRiT82...,https://ipfs.io/ipfs/QmRG2juVPEvFipRkEzUdRBQCU...,https://lh3.googleusercontent.com/tq9bi4bRiT82...,...,Reality Bytes (WTTF Collection),"Look into my eyes, it's plain to see...The fut...",Rarible,OpenSea,2021-04-01 00:00:00,2021-04-01 00:04:49,https://opensea.io/assets/0xd07dc4262bcdbf8519...,"('Rarible', '140105')",Rari,Art
6071021,0x2a46f2ffd99e19a89476e2f62270e0a35bbf0756,51703,0xd67c640b3ec8c590701796d6e317038c6337e25681d5...,0xc11c20ade395abd5aec1a6040f8ee9b5ffd6b6a6,NaN,0x08b5d278a116665aeecf16e60f87891abbbe492a,NaN,https://lh3.googleusercontent.com/8c75baJSPY0b...,https://ipfsgateway.makersplace.com/ipfs/QmSmu...,https://lh3.googleusercontent.com/8c75baJSPY0b...,...,F1AT.,RIP USD.,Makersplace,OpenSea,2021-04-01 00:00:00,2021-04-01 00:03:24,https://opensea.io/assets/0x2a46f2ffd99e19a894...,"('Makersplace', '51703')",Maker,Art
6071022,0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0,16412,0x346561b3f7a233c4245f91c68940b2d750df26ef1b04...,0x9f37284b3a538be8eea2d401b595f44c96d39b70,NaN,0xa353401738e7ec6a4db9c0ee4c66eb5252f681c4,NaN,https://lh3.googleusercontent.com/isSUPEsJJWpF...,https://ipfs.pixura.io/ipfs/QmSHxximuHUZV54pAA...,https://lh3.googleusercontent.com/isSUPEsJJWpF...,...,Pájaro Doctor 13/40,Digital piece made by using a variety of softw...,Superrare,OpenSea,2021-04-01 00:00:00,2021-04-01 00:00:52,https://opensea.io/assets/0xb932a70a57673d89f4...,"('Superrare', '16412')",Superrare,Art

In [ ]:
# # find art NFTs that have been sold more than once
# art_data_by_id = art_data.groupby("Unique_id_collection").count()
# art_data_by_id = art_data_by_id[art_data_by_id["Collection_cleaned"] == 2]
# ids_sold_more_than_once = art_data_by_id.index

# # construct a new dataframe that contains past transaction info
# art_data_sold_more_than_once = art_data[art_data["Unique_id_collection"].isin(ids_sold_more_than_once)]
# art_data_sold_more_than_once = art_data_sold_more_than_once.sort_values(["Unique_id_collection", "Datetime_updated_seconds"], ascending = True).reset_index()
# art_data_sold_more_than_once["Past_Price_USD"] = [list(art_data_sold_more_than_once["Price_USD"])[-1]] + list(art_data_sold_more_than_once["Price_USD"])[0:-1]
# art_data_sold_more_than_once["Past_Datetime_updated"] = [list(art_data_sold_more_than_once["Datetime_updated"])[-1]] + list(art_data_sold_more_than_once["Datetime_updated"])[0:-1]
# art_data_sold_more_than_once["Days_Since_Last_Sell"] = pd.to_datetime(art_data_sold_more_than_once['Datetime_updated']) - pd.to_datetime(art_data_sold_more_than_once['Past_Datetime_updated'])
# art_data_sold_more_than_once = art_data_sold_more_than_once[["Unique_id_collection", "Image_url_1", "Collection_cleaned", "Past_Price_USD", "Price_USD", "Datetime_updated", "Days_Since_Last_Sell"]]
# art_data_cleaned = art_data_sold_more_than_once.iloc[1::2, :]
# art_data_cleaned

# find art NFTs that have been sold more than once
art_data_by_id = art_data.groupby("Unique_id_collection").count()
art_data_by_id = art_data_by_id[art_data_by_id["Collection_cleaned"] > 1]
ids_sold_more_than_once = art_data_by_id.index

# Construct a new dataframe that contains past transaction info
art_data_sold_more_than_once = art_data[art_data["Unique_id_collection"].isin(ids_sold_more_than_once)]
art_data_sold_more_than_once = art_data_sold_more_than_once.sort_values(["Unique_id_collection", "Datetime_updated_seconds"], ascending = True).reset_index()
art_data_sold_more_than_once["Past_Price_USD"] = [list(art_data_sold_more_than_once["Price_USD"])[-1]] + list(art_data_sold_more_than_once["Price_USD"])[0:-1]
art_data_sold_more_than_once["Past_Datetime_updated"] = [list(art_data_sold_more_than_once["Datetime_updated"])[-1]] + list(art_data_sold_more_than_once["Datetime_updated"])[0:-1]
art_data_sold_more_than_once["Days_Since_Last_Sell"] = pd.to_datetime(art_data_sold_more_than_once['Datetime_updated']) - pd.to_datetime(art_data_sold_more_than_once['Past_Datetime_updated'])
art_data_sold_more_than_once = art_data_sold_more_than_once[["Unique_id_collection", "Image_url_1", "Collection_cleaned", "Past_Price_USD", "Price_USD", "Datetime_updated", "Days_Since_Last_Sell"]]
display(art_data_sold_more_than_once)
art_data_sold_more_than_once = art_data_sold_more_than_once[art_data_sold_more_than_once['Unique_id_collection'].duplicated()]
display(art_data_sold_more_than_once)

# Save it to CSV
art_data_sold_more_than_once.to_csv('Cleaned Art Data.csv')

,Unique_id_collection,Image_url_1,Collection_cleaned,Past_Price_USD,Price_USD,Datetime_updated,Days_Since_Last_Sell
0,"('0xmons-xyz', '118')",https://lh3.googleusercontent.com/dcPvU2Mq-sa4...,Xmonsxyz,4.112300,10177.513735,2021-02-25 00:00:00,-46 days
1,"('0xmons-xyz', '118')",https://lh3.googleusercontent.com/dcPvU2Mq-sa4...,Xmonsxyz,10177.513735,15463.965850,2021-04-01 00:00:00,35 days
2,"('0xmons-xyz', '145')",https://lh3.googleusercontent.com/2u3YLHYDvyF_...,Xmonsxyz,15463.965850,19153.699177,2021-03-06 00:00:00,-26 days
3,"('0xmons-xyz', '145')",https://lh3.googleusercontent.com/2u3YLHYDvyF_...,Xmonsxyz,19153.699177,27106.686260,2021-03-21 00:00:00,15 days
4,"('0xmons-xyz', '147')",https://lh3.googleusercontent.com/ZDtyngTO5mC6...,Xmonsxyz,27106.686260,19153.699177,2021-03-06 00:00:00,-15 days
...,...,...,...,...,...,...,...
1055614,"('ultrarare', '1099519685562')",QmRxBgjiHsiRsb2shs7VFKotk6LCvaM8bNopFittcHP32E,Ultra,2.083600,3.523105,2021-03-27 00:00:00,11 days
1055615,"('ultrarare', '1099520059163')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,3.523105,2.990000,2021-04-01 00:00:00,5 days
1055616,"('ultrarare', '1099520059163')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,2.990000,2.497511,2021-04-04 00:00:00,3 days
1055617,"('ultrarare', '1099520059473')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,2.497511,3.173400,2021-04-11 00:00:00,7 days
1055618,"('ultrarare', '1099520059473')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,3.173400,4.112300,2021-04-12 00:00:00,1 days

,Unique_id_collection,Image_url_1,Collection_cleaned,Past_Price_USD,Price_USD,Datetime_updated,Days_Since_Last_Sell
1,"('0xmons-xyz', '118')",https://lh3.googleusercontent.com/dcPvU2Mq-sa4...,Xmonsxyz,10177.513735,15463.965850,2021-04-01 00:00:00,35 days
3,"('0xmons-xyz', '145')",https://lh3.googleusercontent.com/2u3YLHYDvyF_...,Xmonsxyz,19153.699177,27106.686260,2021-03-21 00:00:00,15 days
5,"('0xmons-xyz', '147')",https://lh3.googleusercontent.com/ZDtyngTO5mC6...,Xmonsxyz,19153.699177,27050.954000,2021-03-18 00:00:00,12 days
7,"('0xmons-xyz', '148')",https://lh3.googleusercontent.com/1HIMwxeBA4N-...,Xmonsxyz,19153.699177,27182.641150,2021-03-15 00:00:00,9 days
9,"('0xmons-xyz', '20')",https://lh3.googleusercontent.com/RYYF1CeocGES...,Xmonsxyz,798.493518,12283.810000,2021-03-08 00:00:00,29 days
...,...,...,...,...,...,...,...
1055610,"('ultrarare', '1099519030748')",QmNaFc82cUc6MfseiKGqi5PMX46SB89t6Ypcx9AdZcZN5T,Ultra,57.962500,91.235250,2021-04-09 00:00:00,3 days
1055612,"('ultrarare', '1099519685382')",QmRxBgjiHsiRsb2shs7VFKotk6LCvaM8bNopFittcHP32E,Ultra,3.486750,7.057500,2021-04-11 00:00:00,25 days
1055614,"('ultrarare', '1099519685562')",QmRxBgjiHsiRsb2shs7VFKotk6LCvaM8bNopFittcHP32E,Ultra,2.083600,3.523105,2021-03-27 00:00:00,11 days
1055616,"('ultrarare', '1099520059163')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,2.990000,2.497511,2021-04-04 00:00:00,3 days
1055618,"('ultrarare', '1099520059473')",QmSU7woVNbWkVNfaJeiAaenK8Krjo8hLy25osBWmyDbkdt,Ultra,3.173400,4.112300,2021-04-12 00:00:00,1 days

Index(['('3dpunks', '108895657503177547807713615587106130920312718766249665638523947925102814822401')',
       '('3dpunks', '108895657503177547807713615587106130920312718766249665638523947981177907838977')',
       '('Art-blocks', '10000011')', '('Art-blocks', '10000050')',
       '('Art-blocks', '1000174')', '('Art-blocks', '11000069')',
       '('Art-blocks', '11000269')', '('Art-blocks', '12000265')',
       '('Art-blocks', '12000332')', '('Art-blocks', '13000053')',
       ...
       '('twobontanica', '1099511989418')',
       '('twobontanica', '1099511994639')',
       '('ultrahorrors', '1099513627675')',
       '('ultrahorrors', '1099514002529')',
       '('ultrahorrors', '1099514004287')',
       '('ultrahorrors', '1099514013510')',
       '('ultrahorrors', '1099514031217')',
       '('ultrahorrors', '1099514047770')',
       '('ultrahorrors', '1099520443541')', '('ultrarare', '1099518330401')'],
      dtype='object', name='Unique_id_collection', length=30707)

,Unique_id_collection,Image_url_1,Collection_cleaned,Past_Price_USD,Price_USD,Datetime_updated,Days_Since_Last_Sell
521,"('3dpunks', '108895657503177547807713615587106...",https://lh3.googleusercontent.com/HHreiYU1k5-7...,Dpunk,1253.406000,3563.254200,2021-03-17 00:00:00,0 days
522,"('3dpunks', '108895657503177547807713615587106...",https://lh3.googleusercontent.com/HHreiYU1k5-7...,Dpunk,3563.254200,1817.843661,2021-03-18 00:00:00,1 days
523,"('3dpunks', '108895657503177547807713615587106...",https://lh3.googleusercontent.com/HHreiYU1k5-7...,Dpunk,1817.843661,12672.105929,2021-03-25 00:00:00,7 days

            Price_USD     Datetime_updated
5722005  12672.105929  2021-03-25 00:00:00
5781895   1817.843661  2021-03-18 00:00:00
5789166   3563.254200  2021-03-17 00:00:00
5790061   1253.406000  2021-03-17 00:00:00